### ISSUE TITLE
Create initial Android UI

### ISSUE THREAD

**Issue by ryantobin77** [ryantobin77/0340_EMS_Mobile#5]
Create the initial UI of the Android application that matches the iOS's initial UI as designed previous semester. Create the expanded and collapsed view of the hospitals. Hardcode in dummy data.

<img width="275" alt="Screen Shot 2021-01-22 at 12 08 36 PM" src="https://user-images.githubusercontent.com/42788875/105521918-90e42a80-5caa-11eb-8a87-6bef829e6257.png">

**Comment by amdingler** [comment]
Current division of work:
Allison is working on creating the item view for an individual hospital (xml based)
Anna is working on setting up a recyclerView and recyclerViewAdapter to hold the data and create the views (Java based)
